/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grantme;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Utama extends javax.swing.JFrame {

    private DefaultTableModel model;

    /**
     * Creates new form Utama
     */
    public void loadData1() {
        // menghapus seluruh data
        model.getDataVector().removeAllElements();
        // memberi tahu bahwa data telah kosong
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM beasiswa_dalam_negeri";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                // lakukan penelusuran baris
                Object[] o = new Object[3];
                o[0] = r.getString("id_dalam_negeri");
                o[1] = r.getString("nama_beasiswa");
                o[2] = r.getString("jumlah_kuota");
                
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error tabel dalam negeri");
        }
    }

    private void loadData2() {
        // menghapus seluruh data
        model.getDataVector().removeAllElements();
        // memberi tahu bahwa data telah kosong
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM beasiswa_luar_negeri";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                // lakukan penelusuran baris
                Object[] o = new Object[4];
                o[0] = r.getString("id_luar_negeri");
                o[1] = r.getString("nama_beasiswa");
                o[2] = r.getString("jumlah_kuota");
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error tabel luar negeri");
        }
    }

    // fungsi untuk menampung nilai tabel beasiswa dalam negeri
    // pada halaman home
    private void tabel_dalam_negeri() {
        model = new DefaultTableModel();
        tblDalamNegeri.setModel(model);

        model.addColumn("ID");
        model.addColumn("Nama Beasiswa");
        model.addColumn("Jumlah Kuota");

        loadData1();
    }

    // fungsi untuk menampung nilai tabel beasiswa luar negeri
    //pada halaman home
    private void tabel_luar_negeri() {
        model = new DefaultTableModel();
        tblLuarNegeri.setModel(model);

        model.addColumn("ID");
        model.addColumn("Nama Beasiswa");
        model.addColumn("Jumlah Kuota");

        loadData2();
    }

    private void tabel_dlm_negeri() {
        model = new DefaultTableModel();
        tblDlmNegeri.setModel(model);

        model.addColumn("ID");
        model.addColumn("Nama Beasiswa");
        model.addColumn("Jumlah Kuota");

        loadData1();
    }

    // fungsi untuk menampung nilai tabel beasiswa luar negeri
    private void tabel_lr_negeri() {
        model = new DefaultTableModel();
        tblLrNegeri.setModel(model);
        model.addColumn("ID");
        model.addColumn("Nama Beasiswa");
        model.addColumn("Jumlah Kuota");
        loadData2();
    }

    public Utama() {
        initComponents();
        tabel_dalam_negeri();
        tabel_luar_negeri();
        tabel_dlm_negeri();
        tabel_lr_negeri();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDalamNegeri = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLuarNegeri = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnTambahBeasiswa = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDalamNegeri = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLuarNegeri = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        DalamNegeriPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDlmNegeri = new javax.swing.JTable();
        btnEditDlmNegeri = new javax.swing.JButton();
        btnHapusDlmNegeri = new javax.swing.JButton();
        txtNamaDalam = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtJumlahDalam = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        LuarNegeriPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLrNegeri = new javax.swing.JTable();
        btnEditLrNegeri = new javax.swing.JButton();
        btnHapusLrNegeri = new javax.swing.JButton();
        txtNamaLuar = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtJumlahLuar = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        TambahBeasiswaPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNamaBeasiswa = new javax.swing.JTextField();
        rdDalamNegeri = new javax.swing.JRadioButton();
        rdLuarNegeri = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GrantMe");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\01-KULIAH\\SEMESTER 3\\Pemrograman Lanjut\\Logo_grantme.png")); // NOI18N
        jLabel1.setText("jLabel1");

        btnHome.setBackground(new java.awt.Color(110, 133, 183));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHomeMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOME");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\01-KULIAH\\SEMESTER 3\\Pemrograman Lanjut\\home_grantme.png")); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        btnDalamNegeri.setBackground(new java.awt.Color(110, 133, 183));
        btnDalamNegeri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDalamNegeri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDalamNegeriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDalamNegeriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDalamNegeriMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDalamNegeriMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDalamNegeriMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Beasiswa Dalam Negeri");

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\01-KULIAH\\SEMESTER 3\\Pemrograman Lanjut\\icon_beasiswa.png")); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout btnDalamNegeriLayout = new javax.swing.GroupLayout(btnDalamNegeri);
        btnDalamNegeri.setLayout(btnDalamNegeriLayout);
        btnDalamNegeriLayout.setHorizontalGroup(
            btnDalamNegeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDalamNegeriLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        btnDalamNegeriLayout.setVerticalGroup(
            btnDalamNegeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDalamNegeriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnDalamNegeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        btnLuarNegeri.setBackground(new java.awt.Color(110, 133, 183));
        btnLuarNegeri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuarNegeri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuarNegeriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLuarNegeriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLuarNegeriMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLuarNegeriMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLuarNegeriMouseReleased(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\01-KULIAH\\SEMESTER 3\\Pemrograman Lanjut\\icon_beasiswa.png")); // NOI18N
        jLabel8.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Beasiswa Luar Negeri");

        javax.swing.GroupLayout btnLuarNegeriLayout = new javax.swing.GroupLayout(btnLuarNegeri);
        btnLuarNegeri.setLayout(btnLuarNegeriLayout);
        btnLuarNegeriLayout.setHorizontalGroup(
            btnLuarNegeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLuarNegeriLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLuarNegeriLayout.setVerticalGroup(
            btnLuarNegeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLuarNegeriLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(btnLuarNegeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnTambahBeasiswa.setBackground(new java.awt.Color(110, 133, 183));
        btnTambahBeasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahBeasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahBeasiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahBeasiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahBeasiswaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTambahBeasiswaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTambahBeasiswaMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tambah Beasiswa");

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\01-KULIAH\\SEMESTER 3\\Pemrograman Lanjut\\icon_tambah_beasiswa.png")); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout btnTambahBeasiswaLayout = new javax.swing.GroupLayout(btnTambahBeasiswa);
        btnTambahBeasiswa.setLayout(btnTambahBeasiswaLayout);
        btnTambahBeasiswaLayout.setHorizontalGroup(
            btnTambahBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTambahBeasiswaLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnTambahBeasiswaLayout.setVerticalGroup(
            btnTambahBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTambahBeasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnTambahBeasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogOutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogOutMouseReleased(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(110, 133, 183));
        logout.setText("Log Out");

        javax.swing.GroupLayout btnLogOutLayout = new javax.swing.GroupLayout(btnLogOut);
        btnLogOut.setLayout(btnLogOutLayout);
        btnLogOutLayout.setHorizontalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogOutLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLogOutLayout.setVerticalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDalamNegeri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLuarNegeri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTambahBeasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDalamNegeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLuarNegeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambahBeasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("MENU-HOME");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("BEASISWA YANG ANDA MASUKKAN");

        tblDalamNegeri.setBackground(new java.awt.Color(0, 204, 255));
        tblDalamNegeri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        tblDalamNegeri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDalamNegeri);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("DALAM NEGERI");

        tblLuarNegeri.setBackground(new java.awt.Color(102, 102, 255));
        tblLuarNegeri.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        tblLuarNegeri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblLuarNegeri);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("LUAR NEGERI");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jScrollPane2))
                            .addComponent(jLabel14)))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel11)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addGap(56, 56, 56)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        MainPanel.add(HomePanel, "card2");

        DalamNegeriPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("MENU-BEASISWA DALAM NEGERI");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("BEASISWA DALAM NEGERI YANG TELAH ANDA MASUKKAN");

        tblDlmNegeri.setBackground(new java.awt.Color(51, 204, 255));
        tblDlmNegeri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDlmNegeri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDlmNegeriMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDlmNegeri);

        btnEditDlmNegeri.setBackground(new java.awt.Color(232, 184, 0));
        btnEditDlmNegeri.setText("Perbaharui");
        btnEditDlmNegeri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditDlmNegeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDlmNegeriActionPerformed(evt);
            }
        });

        btnHapusDlmNegeri.setBackground(new java.awt.Color(232, 22, 0));
        btnHapusDlmNegeri.setText("Hapus");
        btnHapusDlmNegeri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusDlmNegeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDlmNegeriActionPerformed(evt);
            }
        });

        txtNamaDalam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNamaDalam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtNamaDalam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaDalamActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Nama Beasiswa");

        txtJumlahDalam.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtJumlahDalam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtJumlahDalam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahDalamActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Jumlah Kuota");

        javax.swing.GroupLayout DalamNegeriPanelLayout = new javax.swing.GroupLayout(DalamNegeriPanel);
        DalamNegeriPanel.setLayout(DalamNegeriPanelLayout);
        DalamNegeriPanelLayout.setHorizontalGroup(
            DalamNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DalamNegeriPanelLayout.createSequentialGroup()
                .addGroup(DalamNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DalamNegeriPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(DalamNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(DalamNegeriPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(DalamNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(DalamNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJumlahDalam, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(txtNamaDalam)))
                            .addGroup(DalamNegeriPanelLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(btnEditDlmNegeri)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusDlmNegeri, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(DalamNegeriPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel15))
                    .addGroup(DalamNegeriPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        DalamNegeriPanelLayout.setVerticalGroup(
            DalamNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DalamNegeriPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addGap(79, 79, 79)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DalamNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaDalam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DalamNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahDalam, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(DalamNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditDlmNegeri, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusDlmNegeri, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        MainPanel.add(DalamNegeriPanel, "card3");

        LuarNegeriPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("MENU-BEASISWA LUAR NEGERI");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("BEASISWA LUAR NEGERI YANG TELAH ANDA MASUKKAN");

        tblLrNegeri.setBackground(new java.awt.Color(102, 102, 255));
        tblLrNegeri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLrNegeri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLrNegeriMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblLrNegeri);

        btnEditLrNegeri.setBackground(new java.awt.Color(232, 184, 0));
        btnEditLrNegeri.setText("Perbaharui");
        btnEditLrNegeri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditLrNegeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLrNegeriActionPerformed(evt);
            }
        });

        btnHapusLrNegeri.setBackground(new java.awt.Color(232, 22, 0));
        btnHapusLrNegeri.setText("Hapus");
        btnHapusLrNegeri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusLrNegeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusLrNegeriActionPerformed(evt);
            }
        });

        txtNamaLuar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNamaLuar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtNamaLuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaLuarActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Nama Beasiswa");

        txtJumlahLuar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtJumlahLuar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtJumlahLuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahLuarActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Jumlah Kuota");

        javax.swing.GroupLayout LuarNegeriPanelLayout = new javax.swing.GroupLayout(LuarNegeriPanel);
        LuarNegeriPanel.setLayout(LuarNegeriPanelLayout);
        LuarNegeriPanelLayout.setHorizontalGroup(
            LuarNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LuarNegeriPanelLayout.createSequentialGroup()
                .addGroup(LuarNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LuarNegeriPanelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel17))
                    .addGroup(LuarNegeriPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(LuarNegeriPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LuarNegeriPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(LuarNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(LuarNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LuarNegeriPanelLayout.createSequentialGroup()
                                .addComponent(btnEditLrNegeri)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusLrNegeri, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LuarNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtJumlahLuar)
                                .addComponent(txtNamaLuar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        LuarNegeriPanelLayout.setVerticalGroup(
            LuarNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LuarNegeriPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel17)
                .addGap(70, 70, 70)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LuarNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaLuar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LuarNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahLuar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(26, 26, 26)
                .addGroup(LuarNegeriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditLrNegeri, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusLrNegeri, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        MainPanel.add(LuarNegeriPanel, "card4");

        TambahBeasiswaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("MENU-TAMBAH BEASISWA");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("SILAHKAN MASUKKAN BEASISWA ANDA");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Nama Beasiswa");

        txtJumlah.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtJumlah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Jumlah Kuota");

        txtNamaBeasiswa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNamaBeasiswa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtNamaBeasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBeasiswaActionPerformed(evt);
            }
        });

        rdDalamNegeri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdDalamNegeri.setText("Dalam Negeri");
        rdDalamNegeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDalamNegeriActionPerformed(evt);
            }
        });

        rdLuarNegeri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdLuarNegeri.setText("Luar Negeri");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Jenis Beasiswa");

        btnTambah.setBackground(new java.awt.Color(110, 133, 183));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambahkan");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TambahBeasiswaPanelLayout = new javax.swing.GroupLayout(TambahBeasiswaPanel);
        TambahBeasiswaPanel.setLayout(TambahBeasiswaPanelLayout);
        TambahBeasiswaPanelLayout.setHorizontalGroup(
            TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahBeasiswaPanelLayout.createSequentialGroup()
                .addGroup(TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TambahBeasiswaPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TambahBeasiswaPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TambahBeasiswaPanelLayout.createSequentialGroup()
                        .addGroup(TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TambahBeasiswaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21))
                            .addGroup(TambahBeasiswaPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))))
                        .addGroup(TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TambahBeasiswaPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(rdDalamNegeri)
                                .addGap(42, 42, 42)
                                .addComponent(rdLuarNegeri, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(TambahBeasiswaPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNamaBeasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                            .addGroup(TambahBeasiswaPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJumlah)
                                    .addGroup(TambahBeasiswaPanelLayout.createSequentialGroup()
                                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(163, 163, 163))
        );
        TambahBeasiswaPanelLayout.setVerticalGroup(
            TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TambahBeasiswaPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel19)
                .addGap(56, 56, 56)
                .addComponent(jLabel20)
                .addGap(52, 52, 52)
                .addGroup(TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaBeasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(TambahBeasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdDalamNegeri)
                    .addComponent(rdLuarNegeri)
                    .addComponent(jLabel23))
                .addGap(39, 39, 39)
                .addComponent(btnTambah)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        MainPanel.add(TambahBeasiswaPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void rdDalamNegeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDalamNegeriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdDalamNegeriActionPerformed

    private void txtNamaBeasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBeasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBeasiswaActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        btnHome.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        btnHome.setBackground(new Color(110, 133, 183));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
        btnHome.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased
        // TODO add your handling code here:
        btnHome.setBackground(new Color(110, 133, 183));
    }//GEN-LAST:event_btnHomeMouseReleased

    private void btnDalamNegeriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDalamNegeriMouseEntered
        // TODO add your handling code here:
        btnDalamNegeri.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnDalamNegeriMouseEntered

    private void btnDalamNegeriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDalamNegeriMouseExited
        // TODO add your handling code here:
        btnDalamNegeri.setBackground(new Color(110, 133, 183));
    }//GEN-LAST:event_btnDalamNegeriMouseExited

    private void btnDalamNegeriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDalamNegeriMousePressed
        // TODO add your handling code here:
        btnDalamNegeri.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnDalamNegeriMousePressed

    private void btnDalamNegeriMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDalamNegeriMouseReleased
        // TODO add your handling code here:
        btnDalamNegeri.setBackground(new Color(110, 133, 183));
    }//GEN-LAST:event_btnDalamNegeriMouseReleased

    private void btnLuarNegeriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuarNegeriMouseEntered
        // TODO add your handling code here:
        btnLuarNegeri.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnLuarNegeriMouseEntered

    private void btnLuarNegeriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuarNegeriMouseExited
        // TODO add your handling code here:
        btnLuarNegeri.setBackground(new Color(110, 133, 183));
    }//GEN-LAST:event_btnLuarNegeriMouseExited

    private void btnLuarNegeriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuarNegeriMousePressed
        // TODO add your handling code here:
        btnLuarNegeri.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnLuarNegeriMousePressed

    private void btnLuarNegeriMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuarNegeriMouseReleased
        // TODO add your handling code here:
        btnLuarNegeri.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnLuarNegeriMouseReleased

    private void btnTambahBeasiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahBeasiswaMouseEntered
        // TODO add your handling code here:
        btnTambahBeasiswa.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnTambahBeasiswaMouseEntered

    private void btnTambahBeasiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahBeasiswaMouseExited
        // TODO add your handling code here:
        btnTambahBeasiswa.setBackground(new Color(110, 133, 183));
    }//GEN-LAST:event_btnTambahBeasiswaMouseExited

    private void btnTambahBeasiswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahBeasiswaMousePressed
        // TODO add your handling code here:
        btnTambahBeasiswa.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnTambahBeasiswaMousePressed

    private void btnTambahBeasiswaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahBeasiswaMouseReleased
        // TODO add your handling code here:
        btnTambahBeasiswa.setBackground(new Color(66, 168, 195));
    }//GEN-LAST:event_btnTambahBeasiswaMouseReleased

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(110, 133, 183));
        logout.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(255, 255, 255));
        logout.setForeground(new Color(110, 133, 183));
    }//GEN-LAST:event_btnLogOutMouseExited

    private void btnLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMousePressed
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(110, 133, 183));
        logout.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnLogOutMousePressed

    private void btnLogOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseReleased
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(255, 255, 255));
        logout.setForeground(new Color(110, 133, 183));
    }//GEN-LAST:event_btnLogOutMouseReleased

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        //untuk meremove semua panel di mainpanel
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        //menampilkan panel yang diinginkan
        MainPanel.add(HomePanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnDalamNegeriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDalamNegeriMouseClicked
        // TODO add your handling code here:
        //untuk meremove semua panel di mainpanel
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        //menampilkan panel yang diinginkan
        MainPanel.add(DalamNegeriPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_btnDalamNegeriMouseClicked

    private void btnLuarNegeriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuarNegeriMouseClicked
        // TODO add your handling code here:
        //untuk meremove semua panel di mainpanel
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        //menampilkan panel yang diinginkan
        MainPanel.add(LuarNegeriPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_btnLuarNegeriMouseClicked

    private void btnTambahBeasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahBeasiswaMouseClicked
        // TODO add your handling code here:
        //untuk meremove semua panel di mainpanel
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        //menampilkan panel yang diinginkan
        MainPanel.add(TambahBeasiswaPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_btnTambahBeasiswaMouseClicked

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        login a = new login();
        a.setVisible(true);
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String Nama_beasiswa = txtNamaBeasiswa.getText().toString().trim();
        String Jumlah_kuota = txtJumlah.getText().toString().trim();
        String dalam_negeri = rdDalamNegeri.getText().toString().trim();
        String luar_negeri = rdLuarNegeri.getText().toString().trim();
        if (dalam_negeri == null) {
            try {
                Connection c = Koneksi.getKoneksi();
                String sql = "INSERT INTO beasiswa_luar_negeri VALUES(?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, "0");
                p.setString(2, Nama_beasiswa);
                p.setString(3, Jumlah_kuota);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "Beasiswa berhasil ditambahkan!");

            }catch (SQLException e) {
                System.out.println("Tambah Beasiswa eror");
            }
        }else{
            try {
                Connection c = Koneksi.getKoneksi();
                String sql = "INSERT INTO beasiswa_dalam_negeri VALUES(?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, "0");
                p.setString(2, Nama_beasiswa);
                p.setString(3, Jumlah_kuota);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "Beasiswa berhasil ditambahkan!");

            }catch (SQLException e) {
                System.out.println("Tambah Beasiswa eror");
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    // fungsi yang akan aktif saat tabel dalam negeri ditekan
    // akan menampilkan data dari tabel ke inputan
    // halaman beasiswa dalam negeri
    private void tblDlmNegeriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDlmNegeriMouseClicked
        // TODO add your handling code here:
        int i = tblDlmNegeri.getSelectedRow();
        if (i == -1) {
// tak ada baris terseleksi return;
        }
        String Nama_beasiswa = (String) model.getValueAt(i, 1);
        txtNamaDalam.setText(Nama_beasiswa);
        String Jumlah_kuota = (String) model.getValueAt(i, 2);
        txtJumlahDalam.setText(Jumlah_kuota);
    }//GEN-LAST:event_tblDlmNegeriMouseClicked

    // fungsi yang akan aktif saat tabel luar negeri ditekan
    // akan menampilkan data dari tabel ke inputan
    // halaman beasiswa luar negeri
    private void tblLrNegeriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLrNegeriMouseClicked
        // TODO add your handling code here:
        int i = tblLrNegeri.getSelectedRow();
        if (i == -1) {
// tak ada baris terseleksi return;
        }
        String Nama_beasiswa = (String) model.getValueAt(i, 1);
        txtNamaLuar.setText(Nama_beasiswa);
        String Jumlah_kuota = (String) model.getValueAt(i, 2);
        txtJumlahLuar.setText(Jumlah_kuota);
    }//GEN-LAST:event_tblLrNegeriMouseClicked

    // fungsi tombol perbaharui untuk memperbaharui data beasiswa dalam negeri
    // pada halaman beasiswa dalam negeri
    private void btnEditDlmNegeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDlmNegeriActionPerformed
        // TODO add your handling code here:
        int i = tblDlmNegeri.getSelectedRow();
        if (i == -1) {
// tidak ada baris terseleksi return;
        }
// ambil id yang terseleksi
        String id = (String) model.getValueAt(i, 0);
        String Nama_beasiswa = txtNamaDalam.getText();
        String Jumlah_kuota = txtJumlahDalam.getText();
        
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "UPDATE beasiswa_dalam_negeri SET nama_beasiswa =?, jumlah_kuota =? WHERE id_dalam_negeri = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, Nama_beasiswa);
            p.setString(2, Jumlah_kuota);
            p.setString(3, id);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error update dalam negeri");
        } finally{
            tabel_dlm_negeri();
        }
    }//GEN-LAST:event_btnEditDlmNegeriActionPerformed

    private void txtNamaDalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaDalamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaDalamActionPerformed

    private void txtJumlahDalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahDalamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahDalamActionPerformed

    // untuk menghapus data yang terpilih pada tabel dalam negeri
    // halaman beasiswa dalam negeri
    private void btnHapusDlmNegeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDlmNegeriActionPerformed
        // TODO add your handling code here:
        int i = tblDlmNegeri.getSelectedRow();
        if (i == -1) {
// tidak ada baris terseleksi
            return;
        }
        String id = (String) model.getValueAt(i, 0);
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "DELETE FROM beasiswa_dalam_negeri WHERE id_dalam_negeri = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.err.println("Terjadi Error Button hapus");
        } finally {
            tabel_dlm_negeri();
        }
        
    }//GEN-LAST:event_btnHapusDlmNegeriActionPerformed

    private void txtNamaLuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaLuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaLuarActionPerformed

    private void txtJumlahLuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahLuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahLuarActionPerformed

    // fungsi tombol perbaharui untuk memperbaharui data beasiswa luar negeri
    // pada halaman beasiswa luar negeri
    private void btnEditLrNegeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLrNegeriActionPerformed
        // TODO add your handling code here:
        int i = tblLrNegeri.getSelectedRow();
        if (i == -1) {
// tidak ada baris terseleksi return;
        }
// ambil id yang terseleksi
        String id = (String) model.getValueAt(i, 0);
        String Nama_beasiswa = txtNamaLuar.getText();
        String Jumlah_kuota = txtJumlahLuar.getText();
        
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "UPDATE beasiswa_luar_negeri SET nama_beasiswa =?, jumlah_kuota =? WHERE id_luar_negeri = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, Nama_beasiswa);
            p.setString(2, Jumlah_kuota);
            p.setString(3, id);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error update dalam negeri");
        } finally{
            tabel_lr_negeri();
        }
    }//GEN-LAST:event_btnEditLrNegeriActionPerformed

    // untuk menghapus data yang terpilih pada tabel luar negeri
    // halaman beasiswa luar negeri
    private void btnHapusLrNegeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusLrNegeriActionPerformed
        // TODO add your handling code here:
        int i = tblLrNegeri.getSelectedRow();
        if (i == -1) {
// tidak ada baris terseleksi
            return;
        }
        String id = (String) model.getValueAt(i, 0);
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "DELETE FROM beasiswa_luar_negeri WHERE id_luar_negeri = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.err.println("Terjadi Error Button hapus");
        } finally {
            tabel_lr_negeri();
        }
    }//GEN-LAST:event_btnHapusLrNegeriActionPerformed

        /**
         * @param args the command line arguments
         */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DalamNegeriPanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel LuarNegeriPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel TambahBeasiswaPanel;
    private javax.swing.JPanel btnDalamNegeri;
    private javax.swing.JButton btnEditDlmNegeri;
    private javax.swing.JButton btnEditLrNegeri;
    private javax.swing.JButton btnHapusDlmNegeri;
    private javax.swing.JButton btnHapusLrNegeri;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnLogOut;
    private javax.swing.JPanel btnLuarNegeri;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel btnTambahBeasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel logout;
    private javax.swing.JRadioButton rdDalamNegeri;
    private javax.swing.JRadioButton rdLuarNegeri;
    private javax.swing.JTable tblDalamNegeri;
    private javax.swing.JTable tblDlmNegeri;
    private javax.swing.JTable tblLrNegeri;
    private javax.swing.JTable tblLuarNegeri;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtJumlahDalam;
    private javax.swing.JTextField txtJumlahLuar;
    private javax.swing.JTextField txtNamaBeasiswa;
    private javax.swing.JTextField txtNamaDalam;
    private javax.swing.JTextField txtNamaLuar;
    // End of variables declaration//GEN-END:variables
}
